### PR TITLE
Add a config to control how often notifications on ACL Source refreshes are sent

### PR DESCRIPTION
**Pull request by thealmightygrant**
First off, this application is awesome. Thank you for writing it.

So, we are receiving a large number of notifications due to timeouts on our ACL Source, and I thought that it might be worthwhile for there to be a config detailing how many failures should be encountered before an error notification is sent. This is common practice in alerting tools, which I believe that the Notification portion of this application falls under.

Please let me know if I completely missed the mark as far as Scala coding conventions go. I am honestly quite a Scala noob. I tried to follow the testing and coding practices that existed in the codebase.

### CODE REVIEW

**Review by simplesteph — CHANGES_REQUESTED** [review]
LGTM

Can you please take care of the README.txt and changelog for documentation?

**Comment by thealmightygrant** [comment]
How does that look on your end? Is that what you were looking for?

**Comment by simplesteph** [comment]
Thanks perfect! Ping me in two weeks for a release, to make sure no bugs are detected

**Comment by thealmightygrant** [comment]
Thanks for getting this in place. We'll start running it in our dev cluster and I'll let you know if we see any issues.

**Pull request merged**
