### PR TITLE
Bug fix for run once mode

### PR DESCRIPTION
**Pull request by andriyfedorov**
Change condition for *run once* mode from `KSM_REFRESH_FREQUENCY_MS=-1` to `KSM_REFRESH_FREQUENCY_MS=0`

### CODE REVIEW

**Comment by simplesteph** [comment]
That's a breaking change and I can't accept that... I don't understand why the value `-1` wouldn't work. Can you add a logging statement, and test the app with your configuration when you try to input the value `-1` ?

**Comment by simplesteph** [comment]
Can you make it `<=0`. I think any negative value or 0 will make sense and that should cover all future cases

**Comment by andriyfedorov** [comment]
> That's a breaking change and I can't accept that... I don't understand why the value `-1` wouldn't work. Can you add a logging statement, and test the app with your configuration when you try to input the value `-1` ?

I am getting exactly the same error if I am trying to use `-1`: java.lang.IllegalArgumentException
Could you please confirm that setting `KSM_REFRESH_FREQUENCY_MS=-1` still works for you as expected?

I just pushed another change to handle `0` and `-1`. I hope this will make change non breaking.

**Comment by andriyfedorov** [comment]
> Can you make it `<=0`. I think any negative value or 0 will make sense and that should cover all future cases

Done.

Thanks for building kafka-security-manager!

**Comment by simplesteph** [comment]
Thanks for the PR!

**Comment by andriyfedorov** [comment]
Would you be able to create release or release candidate with this fix included? Thanks!

**Comment by simplesteph** [comment]
Okay it's released!

https://hub.docker.com/layers/simplesteph/kafka-security-manager/v0.8-release/images/sha256-99b574a2c5077982d603d2fea40e14aacbe75afcd9790fcc5add3ed714d62cf2

**Comment by andriyfedorov** [comment]
Awesome! Thank you very much!

**Pull request merged**
