### PR TITLE
refactor to handle exceptions better

### PR DESCRIPTION
**Pull request by simplesteph**

### CODE REVIEW

**Comment by simplesteph** [comment]
@michellewen1516 please build this branch, and use this in your own environment. Let it run for a while and let me know if you are still encountering issues.

@ntrp sorry this refactor may impact your PR, but I think it'll be a cleaner way of doing things

**Comment by michellewen1516** [comment]
OK, Thanks a lot. @simplesteph

**Comment by michellewen1516** [comment]
@simplesteph Sorry, could you please give me some info about how to test your change? I'd like to test it locally if it is possible.

**Comment by simplesteph** [comment]
@michellewen1516 
```
git pull
git checkout refactor-cleaner-refresh
```

Follow the build instructions here:
https://github.com/simplesteph/kafka-security-manager#building 

and here:
https://github.com/simplesteph/kafka-security-manager#running-on-docker

**Comment by michellewen1516** [comment]
I am running the ksm from this branch. But it didn't happen everyday, so it will be helpful if I can reproduce this bug. Do you have any idea about this? Thanks!

**Comment by simplesteph** [comment]
First, I'd like to make sure KSM with this can run without crashing, so please leave it running for a while.
To simulate some errors, you could block outgoing network traffic on your machine, so that KSM cannot reach the BitbucketCloud and return an HTTP error, a timeout. You could also move the file in Bitbucket (rename it) so that you get a 404 from the requests. Or you could change the username / password temporarily to get a 403. What we want to make sure is that when these errors happen, the ACLs are not reverted (if you block internet access, make sure KSM has still access to Kafka to apply the ACL, otherwise use the 404 or 403 technique)

**Comment by michellewen1516** [comment]
I tested all the cases that you mentioned except the one that " block outgoing network traffic on your machine, so that KSM cannot reach the BitbucketCloud and return an HTTP error".  I failed to reproduce the bug. I think it is better to find a way to reproduce it than check the change in this branch can fix it. Will try.

**Comment by simplesteph** [comment]
if you run both versions side by side, you can see if one of the versions tries to revert the ACL? never tried to run two versions of KSM at the same time but it should work I think

**Comment by michellewen1516** [comment]
@simplesteph  I am sorry to tell you that I got the weird error again when I test using this branch and I can reproduce this bug now.

The logs:

[2020-02-27 17:02:30,657] WARN Method(GET) https://api.bitbucket.org/2.0/repositories/******************/acls.csv failed because connect timed out (skinny.http.HTTP$)
[2020-02-27 17:02:36,821] INFO REMOVED User:*************************************************

Please help to take a look at it when you are available. Thanks.

**Comment by simplesteph** [comment]
Do you have a reliable way of reproducing this? If so can you please let me know the steps you're doing ? I'll try to reproduce on my side and dig into this further

**Comment by michellewen1516** [comment]
Sure, I make my test server do packet loss on egress, the command:  tc qdisc add dev eth0 root netem loss 50%.

I just tested my branch again, seems enableThrowingIOException=true worked

**Comment by simplesteph** [comment]
so on `enableThrowingIOException=true`, you get a timeout, but it's not changing the ACL, whereas this version for sure you get a timeout and it's resetting the ACLs to 0? That is so, so odd.

**Comment by simplesteph** [comment]
Hey, so you're right. On an IO exception, somehow it returns a 200 code (which is completely messed up), and we go into a `textBody` empty to be parsed I guess, and it throws everything absolutely off. That's so messed up. Anyway, the boolean should work. Let me add this to this PR, please test thing (but it should be okay), and we're good to go

**Comment by michellewen1516** [comment]
Great. Please add it, thanks.

**Comment by simplesteph** [comment]
I've merged the changes into master, this will build for a while then it should publish a docker image with `latest`. Please test it extensively, and report in a few days if things work. Then I'll tag this release ASAP because that's a very important fix. Thanks for flagging and working with me on this!

**Pull request merged**
